#!/usr/bin/env python3
"""Composite GSM8K reading for NATIVE (PyTorch, lm-eval) runs -- one line per run, the same rule as the served cells.

The served block-B and natural-lane cells get `exact_match,marker-composite` from `score_natural_lane_lmeval.py`; the
2x2's native halves get it inside `paired_dod_2x2.load_arm`. This is the standalone reporter for any native run
(`run_lmeval_quality.py` output dir, i.e. the directory that holds `samples_gsm8k_*.jsonl`), so a checkpoint
selection table or a single arm-A/B number is produced by the same code path, never by hand.

usage: native_composite.py --run LABEL=/path/to/out/gsm8k [--run ...] [--dataset gsm8k] [--json out.json]
       [--rows out.tex --macros out.tex --macro-prefix vpNat]  [--skip LABEL=0.516 ...] [--base LABEL]
       [--served LABEL=<multi-cell scores.json>:<cell needle> ...]  [--macro-key LABEL=Key ...]
Rows: label & skip (if given) & n & native composite & delta vs --base [& served knee composite & delta vs the served --base].
The served column is the same cell's block-B reading (`score_natural_lane_lmeval.py --eval-split-only`, the `__per_row__` vector),
so a checkpoint-selection table shows the native and the served reading of every candidate from one generator.
"""
from __future__ import annotations

import argparse, json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paired_dod_2x2 import FILTER_COUNTS, load_arm  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", action="append", required=True, help="LABEL=<lm-eval output dir for the dataset>")
    ap.add_argument("--dataset", default="gsm8k", choices=("gsm8k", "coqa", "bbh_cot"))
    ap.add_argument("--skip", action="append", default=[], help="LABEL=<attested chat skip share> (reported beside the score)")
    ap.add_argument("--base", default=None, help="LABEL whose score the deltas are taken against")
    ap.add_argument("--served", action="append", default=[], help="LABEL=<scores.json>:<needle> -- the label's served knee cell (block B)")
    ap.add_argument("--macro-key", action="append", default=[], help="LABEL=Key -- macro stem (default: the label's letters; digits collide)")
    ap.add_argument("--json"); ap.add_argument("--rows"); ap.add_argument("--macros"); ap.add_argument("--macro-prefix", default="vpNat")
    a = ap.parse_args()
    skips = dict(x.split("=", 1) for x in a.skip); keys = dict(x.split("=", 1) for x in a.macro_key)
    served = {}
    for spec in a.served:
        label, rest = spec.split("=", 1); path, needle = rest.rsplit(":", 1)
        sc = json.load(open(path))["__per_row__"]; hits = [k for k in sc if needle in k]
        if len(hits) != 1: sys.exit(f"FATAL: {len(hits)} served cells match {needle!r} for {label}")
        served[label] = 100 * sum(float(o) for o in sc[hits[0]]["ok"]) / len(sc[hits[0]]["ok"])
    out = {}
    for spec in a.run:
        label, root = spec.split("=", 1)
        d = load_arm(root, a.dataset)
        out[label] = {"root": root, "n": len(d), "mean_pct": 100 * sum(d.values()) / len(d),
                      "filters": FILTER_COUNTS.get(root), "skip": (float(skips[label]) if label in skips else None),
                      "served_pct": served.get(label)}
    base = out[a.base]["mean_pct"] if a.base else None
    sbase = out[a.base]["served_pct"] if a.base and out[a.base]["served_pct"] is not None else None
    rows, macros = [], [f"% GENERATED by test/vp/native_composite.py -- native {a.dataset} composite reading per run (same rule as the served cells)."]
    for label, r in out.items():
        r["delta_vs_base_pp"] = (r["mean_pct"] - base) if base is not None and label != a.base else None
        r["served_delta_vs_base_pp"] = (r["served_pct"] - sbase) if sbase is not None and r["served_pct"] is not None and label != a.base else None
        sk = f"{r['skip']:.3f}" if r["skip"] is not None else "--"
        dl = f"{r['delta_vs_base_pp']:+.2f}" if r["delta_vs_base_pp"] is not None else "--"
        row = f"{label} & {sk} & {r['n']} & {r['mean_pct']:.2f} & {dl}"
        if served:
            sv = f"{r['served_pct']:.2f}" if r["served_pct"] is not None else "--"
            sd = f"{r['served_delta_vs_base_pp']:+.2f}" if r["served_delta_vs_base_pp"] is not None else "--"
            row += f" & {sv} & {sd}"
        rows.append(row + " \\\\")
        m = keys.get(label) or re.sub(r"[^A-Za-z]", "", label.title())
        macros.append(f"\\newcommand{{\\{a.macro_prefix}{m}Composite}}{{{r['mean_pct']:.2f}}}")
        if r["delta_vs_base_pp"] is not None:
            macros.append(f"\\newcommand{{\\{a.macro_prefix}{m}DeltaBase}}{{{r['delta_vs_base_pp']:+.2f}}}")
        if r["served_pct"] is not None:
            macros.append(f"\\newcommand{{\\{a.macro_prefix}{m}Served}}{{{r['served_pct']:.2f}}}")
        if r["served_delta_vs_base_pp"] is not None:
            macros.append(f"\\newcommand{{\\{a.macro_prefix}{m}ServedDeltaBase}}{{{r['served_delta_vs_base_pp']:+.2f}}}")
        print(f"{label:22s} n={r['n']} composite {r['mean_pct']:.2f} %  skip {sk}  delta {dl}  served {r['served_pct']}  filters {r['filters']}")
    if a.json: json.dump(out, open(a.json, "w"), indent=1)
    if a.rows: open(a.rows, "w").write("\n".join(rows) + "\n")
    if a.macros: open(a.macros, "w").write("\n".join(macros) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
