#!/usr/bin/env python3
"""Cross-model figure (v1.7): GSM8K at each model's own knee, upstream SGLang vs vSkipper, one point per (model, arm).

x = matched-work mean E2E latency at the knee (seconds; the paired report's absolute mean of that arm over its repetitions),
y = the served composite GSM8K accuracy of the same cell (%, block B, one scored run per arm). Model = marker shape,
system = colour (upstream blue, vSkipper red). No lines, no arrows, no labels inside the axes; the legend sits above the plot.
Every point is bound by explicit keys: --point "MODEL=<paired_report.json>:<dataset>:<rate label>:<scores.json>:<upstream needle>:<hybrid needle>".
The two axes come from their own protocols (the replay lane for latency, the scored lane for accuracy) at the same load.
Macros: \\vpPM<Key>{LatUp,LatHyb,QUp,QHyb,Lat,LatCi,Q,QCi} (Lat/Q = the paired changes, for the text).
"""
import argparse, json, math, sys

MARKERS = ["o", "s", "^", "D", "v"]
BLUE, RED = "#2171b5", "#cb181d"


def t_crit(df):
    for k, v in ((1, 12.706), (2, 4.303), (3, 3.182), (4, 2.776), (5, 2.571), (10, 2.228), (20, 2.086), (30, 2.042), (60, 2.000), (120, 1.980)):
        if df <= k: return v
    return 1.960


def e2e_row(rep, ds, lbl):
    for r in rep["rows"]:
        if r["dataset"] == ds and r["suite"].endswith(lbl) and r["metric"] == "E2E mean":
            return r["baseline_abs"] / 1000, r["treatment_abs"] / 1000, r["mean_pct"], r["ci95_half"], r["n"]
    sys.exit(f"FATAL: no E2E mean row for {ds} {lbl}")


def per_row(sc, needle):
    hits = [k for k in sc["__per_row__"] if needle in k]
    if len(hits) != 1: sys.exit(f"FATAL: {len(hits)} per-row vectors match {needle!r}")
    rec = sc["__per_row__"][hits[0]]
    return {i: float(o) for i, o in zip(rec["ids"], rec["ok"])}


def quality(sc, up_needle, hyb_needle):
    u, h = per_row(sc, up_needle), per_row(sc, hyb_needle)
    common = sorted(set(u) & set(h)); d = [h[k] - u[k] for k in common]; n = len(d); m = sum(d) / n
    sd = math.sqrt(sum((x - m) ** 2 for x in d) / (n - 1)); ci = t_crit(n - 1) * sd / math.sqrt(n)
    return 100 * sum(u.values()) / len(u), 100 * sum(h.values()) / len(h), 100 * m, 100 * ci, n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--point", action="append", required=True); ap.add_argument("--pdf", required=True); ap.add_argument("--macros", required=True)
    ap.add_argument("--macro-key", action="append", default=[], help="MODEL=Key (macro stem; default: the model's letters)")
    ap.add_argument("--macro-prefix", default="vpPM"); ap.add_argument("--ylabel", default="GSM8K accuracy at the knee (%)")
    a = ap.parse_args(); keys = dict(o.split("=", 1) for o in a.macro_key)
    pts = []
    for spec in a.point:
        model, rest = spec.split("=", 1); rep_path, ds, lbl, sc_path, up_needle, hyb_needle = rest.split(":")[:6]
        rep = json.load(open(rep_path)); sc = json.load(open(sc_path))
        lu, lh, dl, dlci, n = e2e_row(rep, ds, lbl); qu, qh, dq, dqci, ndoc = quality(sc, up_needle, hyb_needle)
        pts.append(dict(model=model, lat_up=lu, lat_hyb=lh, dlat=dl, dlat_ci=dlci, n=n, q_up=qu, q_hyb=qh, dq=dq, dq_ci=dqci, ndoc=ndoc))
    import matplotlib; matplotlib.use("Agg"); import matplotlib.pyplot as plt; from matplotlib.lines import Line2D
    fig, ax = plt.subplots(figsize=(3.4, 2.6))
    macros = ["% GENERATED by test/vp/pareto_models_figure.py -- GSM8K at each model's knee: upstream vs vSkipper (E2E s, accuracy %)."]
    handles = []
    for i, p in enumerate(pts):
        mk = MARKERS[i % len(MARKERS)]
        ax.scatter(p["lat_up"], p["q_up"], marker=mk, s=46, color=BLUE, edgecolor="black", linewidth=0.5, zorder=4)
        ax.scatter(p["lat_hyb"], p["q_hyb"], marker=mk, s=46, color=RED, edgecolor="black", linewidth=0.5, zorder=4)
        handles.append(Line2D([], [], marker=mk, color="w", markerfacecolor="#7f7f7f", markeredgecolor="black", markeredgewidth=0.5, markersize=6, label=p["model"]))
        m = keys.get(p["model"]) or "".join(ch for ch in p["model"].title() if ch.isalpha())
        for suf, val, fmt in (("Lat", p["dlat"], "{:+.1f}"), ("LatCi", p["dlat_ci"], "{:.1f}"), ("Q", p["dq"], "{:+.2f}"), ("QCi", p["dq_ci"], "{:.2f}"),
                              ("LatUp", p["lat_up"], "{:.1f}"), ("LatHyb", p["lat_hyb"], "{:.1f}"), ("QUp", p["q_up"], "{:.1f}"), ("QHyb", p["q_hyb"], "{:.1f}")):
            macros.append(f"\\newcommand{{\\{a.macro_prefix}{m}{suf}}}{{{fmt.format(val)}}}")
    systems = [Line2D([], [], marker="o", color="w", markerfacecolor=BLUE, markeredgecolor="black", markeredgewidth=0.5, markersize=6, label="upstream SGLang"),
               Line2D([], [], marker="o", color="w", markerfacecolor=RED, markeredgecolor="black", markeredgewidth=0.5, markersize=6, label="vSkipper")]
    # legend fills column-wise: interleave so row 1 = the models, row 2 = the two systems
    order = []
    for i in range(max(len(handles), len(systems))):
        if i < len(handles): order.append(handles[i])
        if i < len(systems): order.append(systems[i])
    handles = order
    xs = [p["lat_up"] for p in pts] + [p["lat_hyb"] for p in pts]; ys = [p["q_up"] for p in pts] + [p["q_hyb"] for p in pts]
    ax.set_xlim(min(xs) - 6, max(xs) + 6); ax.set_ylim(min(ys) - 3, max(ys) + 3)
    ax.set_xlabel("matched-work mean E2E latency at the knee (s)", fontsize=7); ax.set_ylabel(a.ylabel, fontsize=7)
    ax.tick_params(labelsize=6.5); ax.grid(alpha=0.25)
    ax.legend(handles=handles, fontsize=6, loc="lower center", bbox_to_anchor=(0.5, 1.01), ncol=max(len(pts), 2), frameon=False, handletextpad=0.2, columnspacing=0.8, borderaxespad=0.0)
    fig.tight_layout(); fig.savefig(a.pdf); open(a.macros, "w").write("\n".join(macros) + "\n")
    print(f"{len(pts)} models -> {a.pdf}; {len(macros)-1} macros -> {a.macros}")
    for p in pts:
        print(f"  {p['model']:12s} E2E {p['lat_up']:5.1f} -> {p['lat_hyb']:5.1f} s ({p['dlat']:+.1f} ± {p['dlat_ci']:.1f} %, n={p['n']})  "
              f"accuracy {p['q_up']:.2f} -> {p['q_hyb']:.2f} % ({p['dq']:+.2f} ± {p['dq_ci']:.2f} pp, docs {p['ndoc']})")


if __name__ == "__main__": main()
