#!/usr/bin/env python3
"""Kernel-headroom table for the paper's ablation appendix (v1.6): the count-GEMM's tuned Triton time as a ratio of
cuBLAS on the same packed rows, per op and count band, read from the committed per-device tile artifacts
(`binary_cohort_configs/<device>.json`, fields best_ms / cublas_ms / ratio written by the tuner). No new
measurement: the artifacts are the record of the tune that selected the served tiles.

usage: tile_ratio_table.py --device NVIDIA_A100=A100 --device NVIDIA_RTX_A6000="RTX A6000" --rows out.tex --macros out.tex
"""
from __future__ import annotations

import argparse, json, statistics
from pathlib import Path

OPS = [("gateup", "gate/up (RUN)"), ("down", "down (RUN)"), ("projgd", "gate/down (PROJECT)"), ("projup", "up (PROJECT)")]
MAC = {"NVIDIA_A100": "AHundred", "NVIDIA_H100_HBM3": "Hundred", "NVIDIA_RTX_A6000": "Asix"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", action="append", required=True, help="KEY=label")
    ap.add_argument("--configs", type=Path, default=Path(__file__).resolve().parents[4] / "vskipper/src/vskipper/kernels/binary_cohort_configs")
    ap.add_argument("--rows", type=Path, required=True); ap.add_argument("--macros", type=Path, required=True)
    a = ap.parse_args()
    devs = [d.split("=", 1) for d in a.device]
    arts = {k: json.loads((a.configs / f"{k}.json").read_text()) for k, _ in devs}
    counts = sorted({int(key.split("@")[1]) for art in arts.values() for key in art})
    rows, macros = [], ["% GENERATED by test/vp/tile_ratio_table.py -- tuned Triton count-GEMM time / cuBLAS time on the same rows, from the tile artifacts."]
    for op, label in OPS:
        for c in counts:
            cells = []
            for k, _ in devs:
                rec = arts[k].get(f"{op}@{c}")
                cells.append(f"{rec['ratio']:.2f}" if rec and rec.get("ratio") else "--")
            rows.append(f"{label} & {c:,} & " + " & ".join(cells) + r" \\")
    for k, label in devs:
        r = [v["ratio"] for v in arts[k].values() if v.get("ratio")]
        m = MAC.get(k, k.replace("_", ""))
        macros += [f"\\newcommand{{\\vpTileRatioMed{m}}}{{{statistics.median(r):.2f}}}",
                   f"\\newcommand{{\\vpTileRatioMin{m}}}{{{min(r):.2f}}}", f"\\newcommand{{\\vpTileRatioMax{m}}}{{{max(r):.2f}}}",
                   f"\\newcommand{{\\vpTileHeadroomPct{m}}}{{{(1 - 1/statistics.median(r))*100:.0f}}}"]
    a.rows.write_text("\n".join(rows) + "\n"); a.macros.write_text("\n".join(macros) + "\n")
    print(f"{len(rows)} rows -> {a.rows}; {len(macros)-1} macros -> {a.macros}")
    for k, label in devs:
        r = [v["ratio"] for v in arts[k].values() if v.get("ratio")]
        print(f"  {label}: median {statistics.median(r):.2f} range {min(r):.2f}-{max(r):.2f} over {len(r)} keys")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
